version: '3'
services:
  frontend:
    build:
      context: ../frontend/sort-app
    ports:
      - "3000:3000" 
      
  mongodb:
    image: mongo:latest
    container_name: my-mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  flask-app:
    build:
      context: .
    depends_on:
      - mongodb

volumes:
  mongodb_data:
    driver: local